plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'xyz.gsmhs'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = uri('https://jitpack.io') } // DataGSM SDK 배포 저장소
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // 등록된 프로젝트 저장용 SQLite
    runtimeOnly 'org.xerial:sqlite-jdbc:3.49.1.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects'

    // DataGSM OAuth SDK
    implementation 'com.github.themoment-team:datagsm-oauth-sdk-java:1.5.0'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
